### ISSUE TITLE
Platform wienerlinien not ready yet: None; Retrying in background in 30 seconds

### ISSUE THREAD

**Issue by dominikhoebert** [tofuSCHNITZEL/home-assistant-wienerlinien#2]
The stops don't show up as entitys and I get the following Error message in the HA logs.

```
2022-06-21 18:39:55 WARNING (MainThread) [homeassistant.components.sensor] Platform wienerlinien not ready yet: None; Retrying in background in 30 seconds
2022-06-21 18:39:55 WARNING (MainThread) [homeassistant.components.sensor] Platform wienerlinien not ready yet: None; Retrying in background in 30 seconds
```

**Comment by tofuSCHNITZEL** [comment]
Hi,
what is your HA version?

**Comment by dominikhoebert** [comment]
I was running it on 2022.4 but now I updated to the newest 2022.7
Error still persists. After every HA restart, these entities dont exist for a few hours, then they appear. But become unavailable again after a few days.

**Comment by tofuSCHNITZEL** [comment]
Could you try to open e.g. http://www.wienerlinien.at/ogd_realtime/monitor?rbl=4902 in your browser (preferrably over the same WAN-IP (internet connection) and see if you get some data... maybe you get rate limited and dont receive any data over the api?

**Comment by dominikhoebert** [comment]
The API works always fine for me. I already checked before.
I just found out HA reports the startup time of the wienerlinien integratens with 362 sec. Does this help?

**Comment by tofuSCHNITZEL** [comment]
maybe its fixed with version 1.2.1? could you please try

**Comment by schoeberlt** [comment]
Hi, I have the same issue, @dominikhoebert did you manage to solve this?
@tofuSCHNITZEL I am on 1.2.1 and the issue still exists.

**Comment by schoeberlt** [comment]
It did work with the new beta (1.3.0) though.
